services:
  web:
    container_name: ortt-server
    command: python main.py
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8765:8765"
    volumes:
      - ./:/app
    restart: unless-stopped