services:
  web:
    container_name: ort-server
    command: python main.py
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - "1111:1111"
      - "8765:8765"
    restart: unless-stopped